#!/bin/bash

factorial(){
        n=$1
        fact=1
        for (( i=1; i<=n; i++ ))
        do
                fact=$((fact*i))
        done
        echo $fact


}

read -p "enter n,r :" n r

n_fact=$(factorial $n)
r_fact=$(factorial $r)
nr=$((n-r))
nr_fact=$(factorial $nr)

ncr=$(( n_fact / (r_fact * nr_fact )))




echo "$ncr"
~                                                                                                                                                    
~                                                                                                                                                    
~                                                                                                                                                    
~           
