#!/bin/bash


echo "Enter value for a:"
read a

echo "Enter value for b:"
read b

echo "Enter value for c:"
read c

echo "Enter value for d:"
read d


result=$(echo "scale=2; ($a * 20) - ($b * 2) + ($c / $d)" | bc)


echo "Result: $result"

--------------------------------------------------------------------------------------
[mca@localhost ~]$ vi expr.sh
[mca@localhost ~]$ chmod +x expr.sh
[mca@localhost ~]$ ./expr.sh
Enter value for a:
3
Enter value for b:
4
Enter value for c:
24
Enter value for d:
2
Result: 64.00
