#!/bin/bash

read -p "Enter a 5-digit number: " num


if [[ ! "$num" =~ ^[0-9]{5}$ ]]; then
    echo "Error: Please enter a valid 5-digit number."
    exit 1
fi


reverse=0


while [ $num -gt 0 ]; do
    digit=$((num % 10))
    reverse=$((reverse * 10 + digit))
    num=$((num / 10))
done

echo "Reversed number: $reverse"

-------------------------------------------------------------------------------------
output
[mca@localhost ~]$ vi reversenum.sh
[mca@localhost ~]$ chmod +x reversenum.sh
[mca@localhost ~]$ ./reversenum.sh
Enter a 5-digit number: 45678
Reversed number: 87654

~                 
