#!/bin/bash
current_date_time=$(date)

current_user=$(whoami)

current_directory=$(pwd)
echo "Current Date and Time: $current_date_time"
echo "Current Username: $current_user"
echo "Current Working Directory: $current_directory"
