#!/bin/bash

echo "Enter the file:"
read file

echo "Enter the file:"
read file1

if cmp -s "$file" "$file1"; then
        echo "the both files are sam,e"
        rm $file1
else
        echo "not same"
fi

